### ISSUE TITLE
Icon not centered(merchant's location)

### ISSUE THREAD

**Issue by Claire-pn** [incrementtechnologies/project_rx_web#117]
The icons are not centered.

![image](https://user-images.githubusercontent.com/54086974/94771740-885da080-03ea-11eb-9c68-574b902f0cf9.png)

**Comment by kennCK** [comment]
https://trello.com/c/hMEuZukX/422-test

**Comment by MarionJayMBalugo** [comment]
resolve na man ni sir, with claire

**Comment by Claire-pn** [comment]
done checking
