### ISSUE TITLE
registration unconfirmed password

### ISSUE THREAD

**Issue by aiveejoy** [incrementtechnologies/project_rx_web#13]
Page: Signup/Register Page

Test Cases: With Username of atleast 6 characters long, Email of correct format, Password of atleast 8 characters long with 1 number, 1 special character, 1 capital letter and **is not confirmed**.

Expected results: Users must not be redirected to the dashboard and must be notified of the unconfirmed password inputted.

Actual Results: Redirected to dashboard.

Supporting files:
![issue1](https://user-images.githubusercontent.com/53545806/90760746-e8a1f280-e314-11ea-978b-c31acc67c934.PNG)
![issue2](https://user-images.githubusercontent.com/53545806/90760817-0a02de80-e315-11ea-92ee-2caf2446e37e.PNG)

**Comment by kennCK** [comment]
related to other password issues.
