### ISSUE TITLE
Deposit Action Icon

### ISSUE THREAD

**Issue by aiveejoy** [incrementtechnologies/project_rx_web#136]
Not functionable 

![depositSettingIcon](https://user-images.githubusercontent.com/53545806/96663582-83559680-1383-11eb-8aba-59ac2f6c3dfb.PNG)

**Comment by kennCK** [comment]
https://trello.com/c/Jt8YEYic/420-deposit-action-icon

**Comment by PN25-RicaChristine** [comment]
this is resolved
