### ISSUE TITLE
Fund transfer fee Submit button

### ISSUE THREAD

**Issue by aiveejoy** [incrementtechnologies/project_rx_web#137]
Cannot submit New fund transfer fee

![fundtransferSubmit](https://user-images.githubusercontent.com/53545806/96665441-75a21000-1387-11eb-9cb7-eaf55a6762a3.PNG)

**Comment by kennCK** [comment]
https://trello.com/c/Kz2PDU8v/419-fund-transfer-fee-submit-button

**Comment by MarionJayMBalugo** [comment]
done na ni sir sa dev
