### ISSUE TITLE
Registration with empty password

### ISSUE THREAD

**Issue by aiveejoy** [incrementtechnologies/project_rx_web#14]
Page: Signup/Register

Test Cases: With username, email, **with empty password** 

Expected results: Users must not be redirected to the dashboard and must be notified of the empty Password and Confirm Password Fields.
 
Actual Results: Redirected to Dashboard.

Supporting files

![](https://lh3.googleusercontent.com/-oXzU5QobtrI/Xz5j38HKP0I/AAAAAAAAB8A/DdONTc4VGBI4cIiD6JOG2ldybDwVyQIiwCK8BGAsYHg/s0/isuue2a.PNG)

![](https://lh3.googleusercontent.com/-yuIQVA7tby4/Xz5j6-O7KOI/AAAAAAAAB8M/GY2rlWrZ4VgYlLvlhTvUccV8eiIH9SxfwCK8BGAsYHg/s0/isuue2b.PNG)

**Comment by kennCK** [comment]
@aiveejoy created a separate issue on redirect ha. Registration is fixed, closing this now.
