### ISSUE TITLE
Return Policy Modal Enhancement

### ISSUE THREAD

**Issue by aiveejoy** [incrementtechnologies/project_rx_web#162]
![returnModal](https://user-images.githubusercontent.com/53545806/97381974-3c2c5000-1905-11eb-819e-95a442a0a9e9.PNG)

**Comment by aiveejoy** [comment]
https://trello.com/c/DRYJetUq/441-return-policy-modal-enhancement

**Comment by PN25-RicaChristine** [comment]
@aiveejoy  no data on documents yet

**Comment by PN25-RicaChristine** [comment]
@aiveejoy this will be removed. since information is already included in "Cancellation and Refund Policy"
