### ISSUE TITLE
Print Button(Merchant2)

### ISSUE THREAD

**Issue by aiveejoy** [incrementtechnologies/project_rx_web#19]
Page: Orders Page

Test Cases: Click Print Button

Expected results: Preview and Print Receipt

Actual Results: Nothing happened (Pending)

Supporting files
![printbtn](https://user-images.githubusercontent.com/53545806/91009025-3ae35c00-e612-11ea-967c-0472d5165a7e.PNG)

**Comment by kennCK** [comment]
@CherryMae is working ani pa.
