### ISSUE TITLE
NO record of data reflected on Summary of Sales Chart (RIDER1)

### ISSUE THREAD

**Issue by PN25-RicaChristine** [incrementtechnologies/project_rx_web#20]
Page: DASHBOARD
Test Cases: Selecting month and year. (ANY)
Expected results: There should be a graph (line, bar or any) to show Summary of Sales Record or if there's no record it should display a message like "no data recorded for this month"
Actual Results: NO RECORD OF DATA REFLECTED ON CHART
Supporting files:
![image](https://user-images.githubusercontent.com/54056737/91014007-38393480-e61b-11ea-9c01-0ff8172011fb.png)

**Comment by kennCK** [comment]
This is available only for merchants. Check the mobile App for Riders.
