### ISSUE TITLE
"RunwayExpress User Guide" Modal Content Lack Information (NO INSTRUCTIONS)

### ISSUE THREAD

**Issue by PN25-RicaChristine** [incrementtechnologies/project_rx_web#21]
Page: DASHBOARD
Test Cases: Click "Guide" Tab on the dropdown menu when user icon is clicked
Expected results: Modal should have content to GUIDE user how to use the application
Actual Results:"RunwayExpress User Guide" shows but content lacks information, does not show instructions of how to use the application
Supporting files:
![image](https://user-images.githubusercontent.com/54056737/91015850-6cfabb00-e61e-11ea-868e-b7a5e76f4d71.png)

**Comment by kennCK** [comment]
Hiding this for now as this is not relevant feature.
