### ISSUE TITLE
"Accept & Register Now!" Button Redirection Page(Referral notification via Email) 

### ISSUE THREAD

**Issue by PN25-RicaChristine** [incrementtechnologies/project_rx_web#23]
Module/Page: Signup Page
Specific Feature: Registration Form
Test Cases: Click "Accept & Register Now!" in the referral notification sent via email
![image](https://user-images.githubusercontent.com/54056737/91031472-30858a00-e633-11ea-8ebc-f8bec5c7f70f.png)
Expected Results: Should Redirect to Referred Registration Page
Actual Results: Redirected to a page where there's no registration form
![image](https://user-images.githubusercontent.com/54056737/91031665-7d696080-e633-11ea-8448-4210d1d40fd5.png)

**Comment by kennCK** [comment]
Resolved here https://trello.com/c/aQVMJmcz/199-register-on-referral

**Comment by PN25-RicaChristine** [comment]
Checked 8/28/2020: Fixed
![image](https://user-images.githubusercontent.com/54056737/91524563-18af4e00-e932-11ea-8f59-485f22f7cc82.png)
