### ISSUE TITLE
Search bar in images modal 

### ISSUE THREAD

**Issue by aiveejoy** [incrementtechnologies/project_rx_web#25]
Page: Profile Page

Test Cases : Input something on the search bar

Expected results: auto search image

Actual Results: nothing happened(PENDING)
![searchbar](https://user-images.githubusercontent.com/53545806/91041691-0b007c80-e643-11ea-880d-8692c9c7daf0.PNG)

Supporting files

**Comment by kennCK** [comment]
Resolved
