### ISSUE TITLE
Cannot Update Business information(MERCHANT3)

### ISSUE THREAD

**Issue by TyronIsDemate** [incrementtechnologies/project_rx_web#31]
![Issue#1](https://user-images.githubusercontent.com/54088760/91116847-e3032e80-e6bf-11ea-91ea-553c26a28f45.PNG)
The Update Button is not working hence, the Business Information cannot be updated.

**Comment by kennCK** [comment]
@chloe868 please work ani

**Comment by kennCK** [comment]
This is resolved na
