### ISSUE TITLE
Submit btn Add New Product(merchant2)

### ISSUE THREAD

**Issue by aiveejoy** [incrementtechnologies/project_rx_web#35]
Page: Product page

Test Cases: Fill in the Title and Description, check/uncheck Create as Bundled Product then Click "Submit Button"

Expected results: New product is added on the table.

Actual Results : Product not added.

Supporting files
![addnewProd](https://user-images.githubusercontent.com/53545806/91142679-c2e56680-e6e3-11ea-8914-df745fac6062.PNG)

**Comment by kennCK** [comment]
api
