### ISSUE TITLE
Cancel & "x" btn Add New Product(merchant2)

### ISSUE THREAD

**Issue by aiveejoy** [incrementtechnologies/project_rx_web#37]
Page : Products Page

Test Cases : Fill in Title and Description, check/uncheck Create as Bundled Product then Click Cancel or x Button then click add New Product btn again

Expected results: Fields on modal should now be empty

Actual Results: P input are still on the fields

Supporting files: 
![cancelX_btn](https://user-images.githubusercontent.com/53545806/91144649-e9f16780-e6e6-11ea-84e0-06fea6776f6b.PNG)

**Comment by kennCK** [comment]
@chloe868  resolved.
