### ISSUE TITLE
Missing toggle switch button in Profile Page's Notifications Settings

### ISSUE THREAD

**Issue by PN25-RicaChristine** [incrementtechnologies/project_rx_web#38]
Page: PROFILE PAGE
Test Cases: Click "Notifications" Tab under Personal Settings
Expected results: All notifications settings must have toggle switch button
Actual Results: Account PIN Toggle Switch button (Receive new PIN from email everytime there's a login with my account.) is missing.
Supporting files
![image](https://user-images.githubusercontent.com/54056737/91144735-08576300-e6e7-11ea-8669-3a0deef60ab6.png)

**Comment by kennCK** [comment]
@PN25-RicaChristine please assign ani ni Marion bagud

**Comment by PN25-RicaChristine** [comment]
@kennCK  noted sir.
