### ISSUE TITLE
Search icon appears in front of pop up menus from icons in header when clicked (MERCHANT2)

### ISSUE THREAD

**Issue by PN25-RicaChristine** [incrementtechnologies/project_rx_web#39]
Page: PRODUCT
Test Cases: Clicked store icon (for merchant controls menu) as well as the user icon (for personal&documents menu )
Expected results: Search icon should be behind of the menu
Actual Results: Search icon overrides or displays in front of the menu
Supporting files
![image](https://user-images.githubusercontent.com/54056737/91148910-02648080-e6ed-11ea-8684-f0346c9b4f55.png)
![image](https://user-images.githubusercontent.com/54056737/91148975-11e3c980-e6ed-11ea-938f-b3103208aee0.png)

**Comment by kennCK** [comment]
@chloe868
