### ISSUE TITLE
Search button on Orders(merchant2)

### ISSUE THREAD

**Issue by aiveejoy** [incrementtechnologies/project_rx_web#45]
Page : Orders page

Test Cases: Input/chose date and click search. 

Expected results:  Search orders on specific date

Actual Results: Button not functioning

Supporting files: 
![searchBTN](https://user-images.githubusercontent.com/53545806/91252424-2d53e080-e790-11ea-9f4a-4488715fe042.PNG)

**Comment by kennCK** [comment]
@marion please work

**Comment by MarionJayMBalugo** [comment]
ok sad d i ni sir
