### ISSUE TITLE
Submit button view orders(merchant2)

### ISSUE THREAD

**Issue by aiveejoy** [incrementtechnologies/project_rx_web#46]
Page : Orders page

Test Cases: Click submit button

Expected results : successfully updates order status column on table

Actual Results: Button not functioning

Supporting files : 
![submitOrders](https://user-images.githubusercontent.com/53545806/91253021-66d91b80-e791-11ea-8539-ad4c09a2ec95.PNG)

**Comment by kennCK** [comment]
@chloe868
