### ISSUE TITLE
Cash and Change Undefined values in receipt (merchant2)

### ISSUE THREAD

**Issue by aiveejoy** [incrementtechnologies/project_rx_web#48]
Page:  Orders page

Expected Result: Cash and Change values in receipt are missing 

Actual Result: Cash and Change values are undefined.

Supporting file: 
![receipt](https://user-images.githubusercontent.com/53545806/91258864-f259a900-e79f-11ea-9ca0-ff8c84c032ff.PNG)

**Comment by kennCK** [comment]
API
