### ISSUE TITLE
Search bar Images modal(merchant2)

### ISSUE THREAD

**Issue by aiveejoy** [incrementtechnologies/project_rx_web#49]
Page: Profile page

Test Cases:  Input something on search bar

Expected results: auto search image

Actual Results: Not functioning

Supporting files
![SearchImage](https://user-images.githubusercontent.com/53545806/91265791-909b3e00-e7a3-11ea-8916-20a30245b240.PNG)

**Comment by kennCK** [comment]
@keyrwinz please work nya ani

**Comment by keyrwinz** [comment]
https://github.com/incrementtechnologies/generic/pull/20
