### ISSUE TITLE
Change redirection of link inside the Privacy Policy Modal(USER & RIDER Web)

### ISSUE THREAD

**Issue by PN25-RicaChristine** [incrementtechnologies/project_rx_web#50]
Specific Feature: "here" link in Privacy Policy Modal
Test Cases: Click the "here" link in Privacy Policy Modal
![image](https://user-images.githubusercontent.com/54056737/91266372-b9bbce80-e7a3-11ea-9a59-68701679bb01.png)
Expected results: Should maybe redirect to marketplace page (since users and riders in web  should not be able to access profile page)
Actual Results: Redirected profile page

**Comment by PN25-RicaChristine** [comment]
@kennCK i tried to redirect the USER and RIDER to marketplace page while the MERCHANT and ADMIN are redirected to profile page. Okay rani cya nga redirection sir?

**Comment by kennCK** [comment]
@PN25-RicaChristine please work
