### ISSUE TITLE
checkouts/retrieve_orders and checkout_items/retrieve_on_orders API

### ISSUE THREAD

**Issue by MarionJayMBalugo** [incrementtechnologies/project_rx_web#51]
Sir, na stuck ko diri. inig himo nako sa inventory summary export to pdf and csv kay kailangan ko nga mag for loop sa response sa checkouts/retrieve_orders nga api aron makuha ang respective niya nga items aron himoan nako og summary. Kung ingon ana akong approach kay daghan kaau kog http request nga mahimo using sa for loop.
dili ba pwede nga i sulod nlng sa retrieve_orders and items per order sir?

**Comment by kennCK** [comment]
Will request ni sir ean

**Comment by ecvelayo** [comment]
Papost ani nga issue sa project_rx_api para matrace lang

**Comment by kennCK** [comment]
@MarionJayMBalugo  please ko transfer ani sa https://github.com/incrementtechnologies/project_rx_api
