### ISSUE TITLE
export as PDF and Download as CSV Button(Summary of Orders)

### ISSUE THREAD

**Issue by TyronIsDemate** [incrementtechnologies/project_rx_web#52]
Export as PDF and Download as CSV Button are not working.
![issue4](https://user-images.githubusercontent.com/54088760/91268887-b119c700-e7a8-11ea-8963-206ff497b376.PNG)

**Comment by kennCK** [comment]
@marion please work

**Comment by MarionJayMBalugo** [comment]
ok na d i ni sya kalimot ko.sorry
