### ISSUE TITLE
Inappropriate colors(merchant2)

### ISSUE THREAD

**Issue by aiveejoy** [incrementtechnologies/project_rx_web#53]
Page : Profile page

Test Cases: Inappropriate colors

Expected results: RX colors

Actual Results: Green and Black are the colors used
![wrongColors](https://user-images.githubusercontent.com/53545806/91269086-12da3100-e7a9-11ea-8e91-5602b73da800.PNG)
  

Supporting files

**Comment by kennCK** [comment]
@chloe868
