### ISSUE TITLE
Edit button Issue in Delivery Fee Page (ADMIN)

### ISSUE THREAD

**Issue by PN25-RicaChristine** [incrementtechnologies/project_rx_web#61]
Page: Delivery Fee Page
Test Cases: Click edit button under action column 
Expected results: Should open a modal that will edit the delivery fee info
Actual Results: Nothing happens

Supporting files:
![image](https://user-images.githubusercontent.com/54056737/91442987-44d0bd80-e8a5-11ea-890e-893b171813a5.png)

**Comment by kennCK** [comment]
Resolved
