### ISSUE TITLE
Close Icon on edit product

### ISSUE THREAD

**Issue by kennCK** [incrementtechnologies/project_rx_web#63]
![Screen Shot 2020-08-27 at 8 37 13 PM](https://user-images.githubusercontent.com/9793125/91442922-2a96df80-e8a5-11ea-826f-414f26d0b07e.png)

**Comment by kennCK** [comment]
@PN25-RicaChristine please ko ani

**Comment by PN25-RicaChristine** [comment]
@kennCK na solve nani cya ni ivy sir

**Comment by aiveejoy** [comment]
@PN25-RicaChristine ok2

**Comment by PN25-RicaChristine** [comment]
so this is resolved.
