### ISSUE TITLE
Assign Address Modal Issue in Accounts Page (ADMIN)

### ISSUE THREAD

**Issue by PN25-RicaChristine** [incrementtechnologies/project_rx_web#64]
Page: Accounts Page
Feature: Assign Address Modal
Test Cases:
- Click 'x' button on the upper right corner of the modal
- Click 'Cancel' button in the Modal
- Click 'Submit' button in the Modal with inputs in all fields
- Click 'Submit' button in the Modal without inputs in all field
- Click 'Submit' button in the Modal with lacking inputs in some fields
- Type or search something on the search engine to search location
- Type something on the input fields

Expected results:
- Modal should close when 'x' button or 'Cancel' button are clicked
- There's should be an error or message why it will not submit
- Search engine must work and display something
- When all fields are filled, modal should close when submit button is clicked and shows an alert or message or modal that it is submitted successfully

Actual Results
- Modal should does not close when 'x' button or 'Cancel' button are clicked
- No error message when submit button is clicked when some inputs are unfilled
- Even with all inputs  and submit button is clicked, the modal  won't close and doesn't have any notifications that it is submitted.

Supporting files:
![image](https://user-images.githubusercontent.com/54056737/91445626-f02f4180-e8a8-11ea-973c-596327163aa4.png)
![image](https://user-images.githubusercontent.com/54056737/91445688-03421180-e8a9-11ea-906a-e089b1c87a7e.png)

**Comment by kennCK** [comment]
Resolved on https://trello.com/c/lVZWbi2s/194-admin-account-management
