### ISSUE TITLE
Empty notification settings on profile page

### ISSUE THREAD

**Issue by PN25-RicaChristine** [incrementtechnologies/project_rx_web#68]
Page: Profile Page
Test Cases: Click Notifications tab 
Expected results: Should display the email notifications settings (which has toggle switch buttons to turn on/off  receiving of notifications)
Actual Results: Page displays nothing 
Supporting files:
![image](https://user-images.githubusercontent.com/54056737/91513163-41294f00-e916-11ea-9abf-0ece789ad1f1.png)

issue related to #38

**Comment by kennCK** [comment]
@PN25-RicaChristine  kindly update dao c settings nimo na repository as this is resolve na on live.

**Comment by kennCK** [comment]
@PN25-RicaChristine  assign this to marion if naa pay error

**Comment by PN25-RicaChristine** [comment]
noted sir @kennCK

**Comment by PN25-RicaChristine** [comment]
this is resolved sir
