### ISSUE TITLE
Header issue (landing page and after logging in)

### ISSUE THREAD

**Issue by PN25-RicaChristine** [incrementtechnologies/project_rx_web#73]
Page: Header
Test Case: Zooming in the browser until menu bar appears then clicked menu bar icon then zooming out until menu bar icon disappear
![image](https://user-images.githubusercontent.com/54056737/91703137-4ef80200-ebac-11ea-84d7-014e8c157228.png)
![image](https://user-images.githubusercontent.com/54056737/91703188-620ad200-ebac-11ea-966e-72a6cf90d648.png)
Expected Result: Header duplicates after zooming back out to normal
![image](https://user-images.githubusercontent.com/54056737/91703367-a5fdd700-ebac-11ea-8f75-bd66968b3a90.png)
![image](https://user-images.githubusercontent.com/54056737/91703479-d5144880-ebac-11ea-8ce3-d3462319ec03.png)

**Comment by PN25-RicaChristine** [comment]
@chloe868

**Comment by kennCK** [comment]
@chloe868 resolve naba ni sya? Please close nya if ever
