### ISSUE TITLE
Cannot update location info in admin location management

### ISSUE THREAD

**Issue by PN25-RicaChristine** [incrementtechnologies/project_rx_web#74]
Page: Locations Page (ADMIN)
Test Cases: Click Update button with input in all field
Expected results: Should close the modal and update data
Actual Results:Does not closes the modal and nothing happens does not update data
Supporting files:
![image](https://user-images.githubusercontent.com/54056737/91711712-ef542380-ebb8-11ea-8c12-d913f0dff218.png)

**Comment by kennCK** [comment]
@PN25-RicaChristine  please work ani. I added card on trello

**Comment by PN25-RicaChristine** [comment]
copy sir @kennCK

**Comment by PN25-RicaChristine** [comment]
this is resolved @kennCK
