### ISSUE TITLE
"Type ascending/descending" Sortation  issue in admin accounts

### ISSUE THREAD

**Issue by PN25-RicaChristine** [incrementtechnologies/project_rx_web#75]
Page: Accounts Page
Test Cases:
- Select "Type ascending"
Select "Type descending"
"Type ascending" selected, type some characters (or account type) in search field and enter
"Type descending" selected, type some characters (or account type) in search field and enter

Expected Result: Should display selection or searched according to type of account
Actual Results: Data shows STATUS not TYPE
Supporting files: all are from pagination 1
- For selecting type (ascending and descending)
![image](https://user-images.githubusercontent.com/54056737/91710184-6dfb9180-ebb6-11ea-84f9-36f2fb9f53d9.png)
![image](https://user-images.githubusercontent.com/54056737/91710835-799b8800-ebb7-11ea-88ea-e30f58320f49.png)
- For searching account type
![image](https://user-images.githubusercontent.com/54056737/91710943-a2bc1880-ebb7-11ea-84a8-59fcb175484f.png)
![image](https://user-images.githubusercontent.com/54056737/91710965-aea7da80-ebb7-11ea-88fc-9d786bb6c700.png)
![image](https://user-images.githubusercontent.com/54056737/91711010-c1221400-ebb7-11ea-8a95-9685eed01376.png)
![image](https://user-images.githubusercontent.com/54056737/91711038-d0a15d00-ebb7-11ea-8191-1b15b86335d9.png)
- Searching status (selected type descending or ascending)
![image](https://user-images.githubusercontent.com/54056737/91711185-0f371780-ebb8-11ea-970d-d36c57da65d9.png)
![image](https://user-images.githubusercontent.com/54056737/91712137-c2ecd700-ebb9-11ea-865d-e63e523bef7d.png)

**Comment by kennCK** [comment]
@PN25-RicaChristine please work ani.

**Comment by PN25-RicaChristine** [comment]
copy sir @kennCK

**Comment by PN25-RicaChristine** [comment]
@kennCK  this is fixed
