### ISSUE TITLE
Settings icon issue n Account page (ADMIN)

### ISSUE THREAD

**Issue by PN25-RicaChristine** [incrementtechnologies/project_rx_web#77]
Page: Accounts Page
Test Cases: Click settings icon (under actions column)
Expected results: Should function properly
Actual Results:  Pop up (Scope Location) sometimes not appear in some row, Some settings does not open Assign Address modal and it is sometimes not easy to click
Supporting files:
![image](https://user-images.githubusercontent.com/54056737/91713111-b8334180-ebbb-11ea-8730-c2010ed18907.png)
![image](https://user-images.githubusercontent.com/54056737/91713135-c5e8c700-ebbb-11ea-85ed-cd9daf0749f5.png)

**Comment by kennCK** [comment]
Scope location is viewable only to riders and merchant. So closing this today.
