### ISSUE TITLE
Sign Up Page enhancement

### ISSUE THREAD

**Issue by PN25-RicaChristine** [incrementtechnologies/project_rx_web#81]
PAGE: Sign Up Page
TEST CASE: Click "Register"
EXPECTED RESULT: Should be in line properly
ACTUAL RESULT: Privacy Policy is not lined properly
SUPPORTING FILES:
![image](https://user-images.githubusercontent.com/54056737/91793450-cc724f80-ec4a-11ea-8cc1-b777a1d3b2a5.png)

**Comment by kennCK** [comment]
@PN25-RicaChristine  kindly work ani

**Comment by PN25-RicaChristine** [comment]
fixed sir
