### ISSUE TITLE
Preview button shows empty page merchant

### ISSUE THREAD

**Issue by aiveejoy** [incrementtechnologies/project_rx_web#92]
Page: product/edit

Test Cases: Click Preview button 

Expected results: shows the preview of product details

Actual Results: Shows empty page

Supporting files
![preview button](https://user-images.githubusercontent.com/53545806/92229376-f5f5da00-eedb-11ea-9ed4-18100db13057.PNG)
![previewpage](https://user-images.githubusercontent.com/53545806/92229341-e4143700-eedb-11ea-97ff-0d05099a455e.PNG)

**Comment by kennCK** [comment]
related to https://github.com/incrementtechnologies/project_rx_web/issues/111
